# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 12:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_name', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=12)),
                ('addr', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HalfProduct',
            fields=[
                ('hp_name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('rm', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('hp', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('of_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ven_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('s_id', models.IntegerField(default=0)),
                ('delivery', models.DateTimeField()),
                ('typ', models.BooleanField(default=1)),
                ('receipt_status', models.BooleanField(default=0)),
                ('payment_status', models.BooleanField(default=0)),
                ('total_price', models.FloatField()),
                ('executor', models.IntegerField()),
                ('storage_time', models.DateTimeField()),
                ('is_finish', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFormGoods',
            fields=[
                ('rm_name', models.CharField(max_length=24)),
                ('of_id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutStorDetail',
            fields=[
                ('osd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('num', models.IntegerField()),
                ('batch_number', models.CharField(max_length=8)),
                ('osf_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutStorForm',
            fields=[
                ('osf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('after_s_id', models.DateTimeField()),
                ('staff_id', models.IntegerField()),
                ('check', models.BooleanField(default=0)),
                ('note', models.CharField(max_length=64)),
                ('finished', models.DateTimeField()),
                ('osd_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceForm',
            fields=[
                ('pf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('num', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('assembly_line', models.IntegerField()),
                ('actual_num', models.IntegerField()),
                ('is_instor', models.BooleanField(default=0)),
                ('note', models.TextField()),
                ('is_finish', models.BooleanField(default=0)),
                ('s_id', models.IntegerField()),
                ('qualified_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('rm', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('hp', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('rm_name', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('classification', models.CharField(max_length=8)),
                ('minimum_inventory', models.IntegerField()),
                ('batch_number', models.CharField(max_length=8)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleForm',
            fields=[
                ('sf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('c_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('deliver_date', models.DateTimeField()),
                ('s_id', models.IntegerField()),
                ('state', models.BooleanField(default=0)),
                ('pro_name', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('check', models.BooleanField(default=0)),
                ('out_stor_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleFormProduct',
            fields=[
                ('sf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=8)),
                ('num', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stor',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('valid', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StorDetail',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('s_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SwapForm',
            fields=[
                ('sf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('before_s_id', models.IntegerField()),
                ('after_s_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('check', models.BooleanField(default=0)),
                ('sf_detail_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SwapFormDetail',
            fields=[
                ('sf_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('good_name', models.CharField(max_length=24)),
                ('num', models.IntegerField()),
                ('batch_number', models.CharField(max_length=8)),
                ('sf_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('ven_name', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=24)),
                ('tel', models.CharField(max_length=12)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('rm_name', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=1, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='WasteForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('num', models.IntegerField()),
                ('pf_id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wasteform',
            unique_together=set([('name', 'pf_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='stordetail',
            unique_together=set([('name', 's_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='saleformproduct',
            unique_together=set([('sf_id', 'pro_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderformgoods',
            unique_together=set([('rm_name', 'of_id')]),
        ),
    ]
