# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='delivery',
            field=models.DateTimeField(null=True, verbose_name='交货时间'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='payment_status',
            field=models.BooleanField(default=0, verbose_name='已支付'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='receipt_status',
            field=models.BooleanField(default=0, verbose_name='已收货'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='storage_time',
            field=models.DateTimeField(null=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='total_price',
            field=models.FloatField(null=True, verbose_name='总价'),
        ),
    ]
