# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0002_auto_20180428_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交货时间'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='of_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='订单名称'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='storage_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='typ',
            field=models.BooleanField(default=True, verbose_name='采购订单'),
        ),
        migrations.AlterField(
            model_name='orderformgoods',
            name='batch_number',
            field=models.CharField(blank=True, max_length=8, verbose_name='批次号'),
        ),
        migrations.AlterField(
            model_name='swapform',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='swapform',
            name='sf_name',
            field=models.CharField(max_length=48, unique=True, verbose_name='表名'),
        ),
    ]
